version: "3"
services:
  app:
    build: .
    ports:
      - 13428:13428
    links:
      - database
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
